services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/bookdb
      - JWT_SECRET_KEY=supersecretkey
    depends_on:
      - db
      - ollama

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["sh", "-c", "ollama serve & sleep 10 && ollama pull llama3:8b && tail -f /dev/null"]

volumes:
  postgres_data:
  ollama_data:
